function eng = rpaNozzle(eng, filename)
    %%% This function interpolates the 42 nozzle points generated by
    %%% RPA in order to approximate a spline with hihger spatial fidelity.

    %%% READ IN RPA SPLINE
    rpa = readtable(filename); 
    l = rpa.location;   
    r = rpa.radius; 
    
    %%% INTERPOLATE
    eng.NS = NS;
    eng.l = linspace(0, l(end), eng.NS);
    eng.r = interp1(l, r, L, 'spline');

    %%% NOZZLE ARCLENGTH
    eng.x = zeros(1, eng.NS);
    for i = 2:eng.NS
        eng.x(i) = eng.x(i-1) + sqrt((eng.l(i)-eng.l(i-1))^2 + (eng.r(i)-eng.r(i-1))^2);
    end
end